# Generated by Django 5.0.6 on 2024-05-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'TDescription',
                'verbose_name_plural': 'TDescription',
            },
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='description_6',
        ),
        migrations.AddField(
            model_name='tickets',
            name='description',
            field=models.ManyToManyField(to='event.tdescription'),
        ),
    ]
