# Generated by Django 5.0.6 on 2024-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_tdescription_remove_tickets_description_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='description_m',
            field=models.ManyToManyField(related_name='mute_t_d', to='event.tdescription'),
        ),
    ]
