# Generated by Django 5.0.6 on 2024-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_schedule_day_schedule_description_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
    ]
