# Generated by Django 5.0.6 on 2024-05-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_schedule_day_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedule'},
        ),
        migrations.AlterModelOptions(
            name='schedule_day',
            options={'verbose_name': 'Schedule_Day', 'verbose_name_plural': 'Schedule_Day'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.schedule_day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='speakers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.speakers'),
        ),
    ]
