# Generated by Django 5.0.6 on 2024-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_schedule_day_schedule_day_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_day',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule_day',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, to='event.schedule'),
        ),
    ]
